name: Python application
on: [push]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install pipenv
        run: pip install pipenv    
      - name: Check python formatting
        run: |
          pipenv install --dev
          pipenv run black --check .
